PGM

             STRSBS     SBSD(RDOLIB/RDOPSBSD)
             MONMSG     MSGID(CPF0000)
             DLYJOB     DLY(5)

             STRSBS     SBSD(RDOLIB/RDOISBSD)
             MONMSG     MSGID(CPF0000)
             DLYJOB     DLY(5)

             STRSBS     SBSD(RDOLIB/RDOESBSD)
             MONMSG     MSGID(CPF0000)
             DLYJOB     DLY(5)

             SNDPGMMSG  MSG('DevOps Portal Iniciado revisar ADDLIBLE +
                          RDOLIB + WRKRDO')

ENDPGM
